###########################################
#
# To Use, Download the RestClient Extension in VS Code
#
##########################

@baseUrl = http://localhost:8080/src/controller 
@contentType = application/x-www-form-urlencoded

#####
# User CRUDs
#####

###

GET {{baseUrl}}/UserController?func=all

###

GET {{baseUrl}}/UserController?func=get&user_id=2

###

POST {{baseUrl}}/UserController
Content-Type: application/x-www-form-urlencoded

func=add
&user_id=15
&user_name=professorX
&pw=xmen
&first_name=Charles
&last_name=Xavier
&email=professorx@marvel.com

###

POST {{baseUrl}}/UserController
Content-Type: application/x-www-form-urlencoded

func=del
&user_id=15

###

#################################
# Filter
##############################

POST {{baseUrl}}/FilterController
Content-Type: application/x-www-form-urlencoded

func=filt
&filt_str=2009

######################################
# Tribute
###############################


GET {{baseUrl}}/TributeController?func=all

###

GET {{baseUrl}}/TributeController?func=get&id=15

###

GET {{baseUrl}}/TributeController?func=allByUser&user_id=1

###

POST {{baseUrl}}/TributeController
Content-Type: application/x-www-form-urlencoded

func=add
&user_id=5
&dec_id=1
&tribute="Hey was a good man/woman"
&id=15
&dt_post=2022-10-23

###

POST {{baseUrl}}/TributeController
Content-Type: application/x-www-form-urlencoded

func=del
&id=15

###########################
# Cemeteries 
#################

GET {{baseUrl}}/CemController?func=all

###

GET {{baseUrl}}/CemController?func=get&cem_id=3

###

POST {{baseUrl}}/CemController
Content-Type: application/x-www-form-urlencoded

func=add
&cem_id=6
&con_id=2
&cem_name=O. H. Pye III Funeral Home
&cem_city= Detroit
&cem_comments=

###

POST {{baseUrl}}/CemController
Content-Type: application/x-www-form-urlencoded

func=del
&cem_id=6

###

###########################
# Countries
####################